#include "sys.h"
#include "tests/acp_test_declarations.h"

void run_acp_tests()
{
  test_acp_prompt_content_capabilities_and_strict_validation();
  test_acp_typed_session_update_mapper_ordering_and_limits();
  test_acp_permission_dtos_show_bounded_actions();
  test_acp_codec_envelopes_and_ids();
  test_acp_codec_initialize_meta_additive_and_malformed_fields();
  test_acp_codec_utf8_depth_size_and_serialization();
  test_acp_transport_lf_crlf_and_final_record();
  test_acp_service_gating_reinitialize_and_negotiation();
  test_acp_service_mutating_request_terminal_commits();
  test_acp_session_request_schema_defaults_and_invalid_item_skipping();
  test_acp_session_capacity_is_reserved_before_persistence();
  test_acp_startup_model_is_pinned_across_config_mutation();
  test_acp_resume_projects_history_for_pinned_startup_model();
  test_acp_session_lifecycle_real_prompt_and_provider_ownership();
  test_acp_exact_identity_persisted_cwd_and_restart();
  test_acp_cross_process_lease_and_bounded_streaming();
  test_acp_list_pagination_cancel_race_stop_reasons_and_file_safety();
  test_acp_cancel_terminal_arbitration_and_provider_setup_paths();
  test_acp_critical_commands_remain_one_shot();
  test_acp_session_mcp_requires_persistent_operator_authorization();
  test_acp_strict_session_mcp_registry_and_error_propagation();
  test_acp_negotiated_client_filesystem_and_terminal_routing();
  test_acp_builtin_permission_gateway_one_shot_mutations_and_updates();
  test_acp_session_grant_cannot_follow_retargeted_parent_symlink();
  test_acp_session_cwd_allows_symlinked_workspace_path();
  test_acp_permission_once_always_reject_cancel_invalid_and_hard_policy_matrix();
  test_acp_close_timeout_is_internal_error_with_eventual_cleanup();
  test_acp_peer_prompt_terminal_commit_arbitration();
  test_acp_client_tool_dtos_lifecycle_and_cancellation();
  test_acp_peer_lifecycle_notifications_and_duplicate_ids();
  test_acp_peer_shutdown_cancels_blocked_transport();
  test_acp_peer_bidirectional_out_of_order_deadline_and_late_response();
  test_acp_peer_cancel_duplicate_inflight_and_saturation();
  test_acp_peer_lifecycle_request_commit_linearization();
  test_acp_peer_outbound_queue_saturation();
  test_acp_peer_delivered_fail_stop_cancellation();
  test_acp_peer_fail_stop_poison_arbitrates_all_pending_calls();
  test_acp_peer_writer_acknowledged_lifecycle();
  test_acp_peer_claimed_outbound_abort_and_delivery_races();
  test_acp_prompt_admission_rollback_and_control_cancel_saturation();
  test_acp_peer_shutdown_abandons_queued_unstarted_request();
  test_acp_peer_started_non_cooperative_shutdown_escalates();
  test_acp_redacted_command_audit_omits_recipe_arguments();
  test_acp_peer_write_failure_wakes_reader_and_shutdown_race();
}
