#include "sys.h"
#include "tests/session_test_declarations.h"

void run_session_tests()
{
  session_tests::test_session_store_round_trip();
  session_tests::test_bounded_session_reads_strictly_classify_framed_records();
  session_tests::test_ephemeral_session_store_stays_in_memory();
  session_tests::test_session_record_round_trip();
  session_tests::test_session_tree_metadata_entries_validate_and_export();
  session_tests::test_subagent_job_history_round_trip_malformed_bounds_and_legacy();
  session_tests::test_subagent_job_history_projection_fork_filter_and_unmatched_start();
  session_tests::test_subagent_job_history_is_excluded_from_provider_replay();
  session_tests::test_session_tree_index_derives_branches();
  session_tests::test_session_tree_index_handles_parent_cycles();
  session_tests::test_session_branch_fork_and_clone_copy_source_safely();
  session_tests::test_session_branch_summary_appends_to_source_session();
  session_tests::test_session_branch_summary_coverage_bounds_and_duplicates();
  session_tests::test_session_stats_helper();
  session_tests::test_session_stats_saturates_large_usage_and_costs();
  session_tests::test_session_stats_omits_incomplete_cost_total();
  session_tests::test_session_stats_flags_legacy_assistant_tokens_without_cost();
  session_tests::test_assistant_output_v4_session_schema_and_replay();
  session_tests::test_session_stats_projects_mixed_v3_v4_history();
  session_tests::test_session_replay_validation();
  session_tests::test_session_lease_creation_and_link_safety();
  session_tests::test_session_torn_tail_recovery();
  session_tests::test_session_torn_tail_listing();
  session_tests::test_session_resume_and_listing();
  session_tests::test_compaction_snapshot_matcher_is_exact();
  session_tests::test_session_compaction_entry_round_trip();
  session_tests::test_session_markdown_export();
  session_tests::test_session_portable_jsonl_sanitizer();
  session_tests::test_compaction_config_and_thresholds();
  session_tests::test_compaction_context_reconstruction();
  session_tests::test_tool_content_parts_reconstruction();
  session_tests::test_portable_omitted_reasoning_is_dropped_from_provider_replay();
  session_tests::test_image_attachment_message_reconstruction_and_validation();
  session_tests::test_synthetic_delivery_provenance_validation();
  session_tests::test_image_attachment_storage_boundary();
  session_tests::test_image_attachment_import();
  session_tests::test_created_session_rollback_is_identity_safe_and_preserves_attachments();
  session_tests::test_lease_bound_session_reads_hold_exact_authority();
  session_tests::test_session_read_authority_binding_and_descriptor_lifetime();
  session_tests::test_session_read_authority_retains_runtime_policy();
  session_tests::test_session_read_authority_identity_fingerprint_and_clamp();
  session_tests::test_assistant_output_append_target_state_and_batches();
  session_tests::test_incomplete_assistant_output_suffix_recovery();
  session_tests::test_session_append_authority_and_commit_state();
  session_tests::test_logical_session_projection_v4_public_privacy_and_compatibility();
  session_tests::test_provider_base64_encoding();
}
