#pragma once

#include "BasicWindow.h"
#include "GraphemeSurface.h"
#include "HorizontalLayout.h"
#include "Paragraph.h"

#include <optional>

namespace ava::tui::terminal {

class GraphemeSurface;

// class Pad
//
// Represents an ncurses pad: an off-screen terminal buffer that is not restricted
// by the screen size and that is shown on the screen by refreshing explicit
// rectangles (prefresh).
//
// The content of the pad is a list of HorizontalLayout's. Appending a HorizontalLayout
// does not create or update the underlying ncurses pad; call generate() to (re)create
// it from the current content.
//
class Pad
{
 protected:
  static constexpr uint32_t growth_slack_rows = 16;

 protected:
  using horizontal_layouts_type = std::vector<HorizontalLayout, core::Application::Vec8Alloc::rebind<HorizontalLayout>::other>;

  horizontal_layouts_type horizontal_layouts_;          // The HorizontalLayout's that make up the content of this pad, in order.
  GraphemeSurface fitted_horizontal_layouts_;           // The grapheme clusters that make up this pad; (re)initialized by a call to generate_grapheme_surface.
  bool blank_line_between_block_rows_;                  // The last blank_line_between_block_rows used with generate_grapheme_surface.
  bool fitted_horizontal_layouts_up_to_date_{false};    // True iff fitted_horizontal_layouts_ is up to date.
  std::optional<BasicWindow> pad_;                      // The ncurses pad created by the last generate() call, if any.
  uint32_t content_rows_{};                             // The number rows of content: the height of the GraphemeSurface returned
                                                        // by generate_grapheme_surface, or somehow updated equivalent of that.

 protected:
  // Generate all block rows fitted to `columns` without creating or writing an ncurses pad.
  //
  // The returned surface retains views into the LayoutItem objects owned by this Pad and must not
  // outlive them. At least one non-empty HorizontalLayout must have been appended.
  void generate_grapheme_surface(columns_t columns, bool blank_line_between_block_rows = true);

 public:
  Pad() : horizontal_layouts_(core::Application::instance().vec8alloc()) { }

  // Append `horizontal_layout` to the end of the content of this pad.
  void append(HorizontalLayout&& horizontal_layout) { horizontal_layouts_.push_back(std::move(horizontal_layout)); }

  // Finalize and append `paragraph` as a one-item HorizontalLayout at the end of this pad.
  //
  // This compatibility overload performs the Paragraph width initialization that callers adding
  // a Paragraph directly to a HorizontalLayout must perform themselves.
  void append(std::unique_ptr<Paragraph>&& paragraph)
  {
    paragraph->initialize_cached_natural_width();
    HorizontalLayout horizontal_layout;
    horizontal_layout.append(std::move(paragraph));
    horizontal_layouts_.push_back(std::move(horizontal_layout));
  }

  // (Re)generate the ncurses pad from the current content, fitting each HorizontalLayout to `columns` terminal columns.
  //
  // The ncurses pad is created with at least `columns` terminal columns and a height that fits all wrapped rows.
  // Its width can be larger when a layout's minimum widths require it. A single blank row is inserted between
  // consecutive HorizontalLayout's iff `blank_line_between_block_rows` is true.
  // A pad generated by an earlier call, if any, is destroyed.
  // The terminal must have been initialized (Context) before calling this function.
  void generate();

  // Calls pad_.prefresh.
  void prefresh(Position pad_pos, Position screen_pos, Dimension viewport_size);

  // Accessor.
  horizontal_layouts_type const& horizontal_layouts() const { return horizontal_layouts_; }

  // Return the number of terminal rows of content.
  uint32_t content_rows() const { return content_rows_; }

  // Return the dimensions of the generated ncurses pad.
  Dimension dimension() const;

  // Access the ncurses pad BasicWindow underlying this pad; for example for input functions that
  // must not implicitly refresh stdscr over the pad (see BasicWindow::get_wch).
  BasicWindow& basic_window();

  AVA_DEBUG_PRINT_MEMBERS_ON
};

} // namespace ava::tui::terminal
